### ISSUE TITLE
import-next-hop does not work

### ISSUE THREAD

**Issue by steveyiyo** [natesales/pathvector#102]
**Describe the bug**
`import-next-hop` does not work, it only generates the below config.

```
bgp_next_hop = 10.0.0.1;
```

According to the relevant documentation, you may need to change the BIRD config to this.

```
bgp_next_hop = 10.0.0.1;
gw = bgp_next_hop;
```

**Environment**
```
Pathvector 5.10.2 commit e8a44c8673c18b1d676a4980ff003539933d236f date 2022-02-12T08:15:40Z
No plugins
```

**To Reproduce**
```
templates:
  upstream:
    allow-local-as: true
    announce-communities: [ "60614,100" ]
    remove-all-communities: 60614
    local-pref: 350
    import-communities: [ "60614,200" ]
    enforce-peer-nexthop: false

  Nate:
    asn: 34553
    template: upstream
    neighbors:
      - 44.190.42.3
      - 2602:801:30ff::3
    import-next-hop: "10.0.0.1"
    pre-export: if net ~ [ 103.x.x.x/23 ] then bgp_path.prepend(12345); else reject;
```

**Expected behavior**
next-hop will work fine.
