### ISSUE TITLE
IPv6 optimizer config

### ISSUE THREAD

**Issue by TheresaQWQ** [natesales/pathvector#138]
**What feature would you like to see?**
![image](https://user-images.githubusercontent.com/22370654/199527562-448814ea-9eb1-421b-827d-8eb68f30002c.png)

**Comment by netstx** [comment]
Did you configure the peer with 'probe-sources' parameter? It does work with IPv6 as far as I can tell.

https://pathvector.io/docs/configuration#probe-sources

**Comment by TheresaQWQ** [comment]
yes i configured, still have this error, and my config file is below
![image](https://user-images.githubusercontent.com/22370654/200083397-ed6f5378-b113-4cf6-99ff-384fea637370.png)

```
asn: xxxxxx
router-id: xxx
source6: 2406:xxx

bird-directory: /etc/bird
default-route: false

prefixes:
  - 2406:xxx

optimizer:
  probe-interval: 30
  targets:
    - Target1
    - Target2

peers:
  Vultr:
    asn: 64515
    probe-sources: [2406:xxxx]
    template: upstream
    password: ######
    multihop: true
    neighbors:
      - 2001:xxxx
```
