### ISSUE TITLE
source6 doesn't seem to work while using srd-communities

### ISSUE THREAD

**Issue by andrewnyr** [natesales/pathvector#151]
**Describe the bug**
When using srd-communities to allow routes into the kernel, source6 seems to be ignored.

**Environment**

1. Pathvector 6.1.0 Built bac2d58d5e14685506a4552024641b23d883933e on 2023-01-06T08:30:05Z Plugins: (none)
2. Ubuntu 22.04.1 LTS x86_64
3. See:
```
asn: 1003
router-id: 170.39.230.89
rtr-server: rtr.rpki.cloudflare.com:8282
irr-server: rr.ntt.net
source6: 2602:fc26:6::0
keep-filtered: true
local-communities: [ "1003,1299" ]

kernel:
 srd-communities: [ "1003,1203" ]

  ONIXRS:
    asn: 57369
    disabled: false
    listen4: 149.112.50.21
    listen6: 2001:504:125:e1::21
    filter-transit-asns: true
    auto-import-limits: true
    enforce-peer-nexthop: false
    enforce-first-as: false
    strict-rpki: false
    remove-all-communities: 1003
    local-pref: 90
    announce: [ "1003,203", "1003,200" ]
    add-on-import: [ "1003,1203", "1003,1200" ]
    neighbors:
      - 149.112.50.1
      - 2001:504:125:e1::1
      - 149.112.50.2
      - 2001:504:125:e1::2
```

**To Reproduce**

1. Copy this config to pathvector.yml...
2. Run `pathvector generate`
3. ip -6 route shows routes exported to kernel but no src

**Expected behavior**

I expect the routes in kernel to have a src of what I set in source6.
