### ISSUE TITLE
only-announce issue

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#166]
**Describe the bug**

only-announce can't be used even announce-all aren't configured

**Environment**

1. Output from `pathvector version`
```
Pathvector 6.1.0
Built bac2d58d5e14685506a4552024641b23d883933e on 2023-01-06T08:30:05Z
Plugins: (none)
```
2. OS version
Debian 11
3. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier]
```
templates:
  upstream:
    add-on-import:
      - 199514:1:1
    allow-local-as: true
    announce:
      - 199514:1:4
    local-pref: 100
    remove-all-communities: 199514

peers:
############
# UPSTREAM #
############
  Cloudie_Upstream:
    asn: 924
    disabled: false
    only-announce:
      - "2a0a:280:b00b::/48"
      - "2a12:dd47:8046::/48"
    listen6: "2602:fba1:d00::116:1"
    local-pref: 100
    neighbors:
      - "2602:fba1:d00::1"
    template: upstream
```

**To Reproduce**

1. Use that config above
2. Run `pathvector g`
3. See error
```
INFO[0000] Starting Pathvector 6.1.0
FATA[0000] [Cloudie_Upstream] only-announce and announce-all cannot both be set
```

**Expected behavior**

It's should be works, since announce-all aren't configured at all

**Comment by caguiclajmg** [comment]
Haven't tried but you can probably work around this by forcing `announce-all` to null.

`announce-all` is false by default not nil so it fails this check when setting `only-announce`:
https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/process/process.go#L256

https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/config/config.go#L183

https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/config/config.go#L204

Maybe change `only-announce` default to nil as well (but you'd have to handle nils in `BirdSet` or in the template) or change the check to a non-empty list or nil instead of just nil.

**Comment by rapdodge** [comment]
> Haven't tried but you can probably work around this by forcing `announce-all` to null.
> 
> `announce-all` is false by default not nil so it fails this check when setting `only-announce`:
> 
> https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/process/process.go#L256
> 
> https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/config/config.go#L183
> 
> https://github.com/natesales/pathvector/blob/1bcaaa36204ddc0c7a63fa7fe547c0cddbd43b24/pkg/config/config.go#L204
> 
> Maybe change `only-announce` default to nil as well (but you'd have to handle nils in `BirdSet` or in the template) or change the check to a non-empty list or nil instead of just nil.

Nope, still no
```
peers:
############
# UPSTREAM #
############
  Cloudie_Upstream:
    announce-all: null
    asn: 924
    disabled: false
    listen6: "2602:fba1:d00::116:1"
    local-pref: 100
    neighbors:
      - "2602:fba1:d00::1"
    only-announce:
      - "2a0a:280:b00b::/48"
      - "2a12:dd47:8046::/48"
    template: upstream
```

```
root@bismillah-cloudie:~# pathvector g
INFO[0000] Starting Pathvector 6.1.0
FATA[0000] [Cloudie_Upstream] only-announce and announce-all cannot both be set
```
