### ISSUE TITLE
Adding source4 or source6 does not set KRT route

### ISSUE THREAD

**Issue by lucyrose39** [natesales/pathvector#168]
**Describe the bug**
Adding source4 or source6 does not set KRT route in bird, causing routing failures on the machine.

**Environment**
1. Output from `pathvector version`
```
Pathvector 6.1.0
Built bac2d58d5e14685506a4552024641b23d883933e on 2023-01-06T08:30:05Z
Plugins: (none)
```
2. OS version
Debian 11.6
3. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
```yaml
asn: 54681
router-id: 128.254.226.6
keep-filtered: true
default-route: false
source4: 128.254.226.6
source6: 2a06:a005:150a:1::1
irr-server: rr.level3.net
prefixes:
  - [prefixes here]

templates:
  upstream:
    allow-local-as: true
    announce: [ "65510,15", "65510:0:15", "65510,20", "65510:0:20" ]
    remove-all-communities: 65510
    local-pref: 80
    add-on-import: [ "65510,12", "65510:0:12" ]

  routeserver:
    filter-transit-asns: true
    auto-import-limits: true
    enforce-peer-nexthop: false
    enforce-first-as: false
    announce: [ "65510,15", "65510:0:15" ]
    remove-all-communities: 65510
    local-pref: 90
    add-on-import: [ "65510,13", "65510:0:13" ]

  peer:
    filter-irr: true
    filter-transit-asns: true
    auto-import-limits: true
    auto-as-set: true
    announce: [ "65510,15", "65510:0:15" ]
    remove-all-communities: 65510
    local-pref: 100
    add-on-import: [ "65510,14", "65510:0:14" ]

  downstream:
    filter-irr: true
    filter-rpki: true
    allow-blackhole-community: true
    filter-transit-asns: true
    auto-import-limits: true
    auto-as-set: true
    announce: [ "65510,15", "65510:0:15" ]
    announce-default: true
    remove-all-communities: 65510
    local-pref: 200
    add-on-import: [ "65510,15", "65510:0:15" ]

  nopeerdb:
    filter-irr: true
    allow-blackhole-community: true
    filter-transit-asns: true
    auto-import-limits: false
    auto-as-set: false
    announce: [ "65510,15", "65510:0:15" ]
    announce-default: true
    remove-all-communities: 65510
    local-pref: 200
    add-on-import: [ "65510,15", "65510:0:15" ]

  backbone:
    filter-irr: false
    filter-transit-asns: false
    allow-local-as: true
    next-hop-self: true
    force-peer-nexthop: true
    pre-import-filter: 'accept;'
    announce: [ "65510,15", "65510,14", "65510,13", "65510,20" ]

  allr:
    filter-irr: false
    filter-transit-asns: false
    allow-local-as: true
    next-hop-self: true
    force-peer-nexthop: true
    pre-import-filter: 'accept;'
    announce: [ "65510,15", "65510,14", "65510,13", "65510,12", "65510,20" ]
kernel:
    learn: true
    export: true
    srd-communities: [ "65510,12", "65510,13", "65510,14", "65510,15" ]

peers:
  up1:
    asn: xxx
    template: upstream
    filter-rpki: true
    multihop: true
    neighbors:
      - x.x.x.x
      - ::1

  onix:
    asn: 57369
    next-hop-self: true
    template: routeserver
    filter-rpki: true
    pre-import-filter: |
      if (bgp_path ~ [=  6939 * =]) then  reject;
    import-limit4: 10000
    import-limit6: 10000
    neighbors:
      - 149.112.50.1
      - 149.112.50.2
      - 2001:504:125:e1::1
      - 2001:504:125:e1::2
```
**To Reproduce**
1. Copy this config to pathvector.yml...
2. Add peers of your own
3. Run `pathvector generate`
4. check bird.conf, there is no KRT route specified

**Expected behavior**
KRT route should be added, and the specified IP address should always be used to go towards the internet on the box
