### ISSUE TITLE
Import limits not respected

### ISSUE THREAD

**Issue by mctom987** [natesales/pathvector#172]
Import limits defined in pathvector.yml are not used when generating bird conf.

```sh
root@yyz1:~# pathvector version
Pathvector 6.2.1
Built 52583222f5d11d7f232d4c34a256abea7a4fa5eb on 2023-04-07T03:44:56Z
No plugins
BIRD: 2.0.7

root@yyz1:~# cat /etc/bird/AS6939_AS6939.conf | head -n 5
# as6939 AS6939
define AS6939_AS6939_IMPORT_v4 = 185000;
define AS6939_AS6939_IMPORT_v6 = 100000;

protocol bgp AS6939_AS6939_v4 {
```

Relevant YML:
```yml
  as6939:
    template: peer
    asn: 6939
    filter-irr: false
    import-limit4: 250000
    import-limit6: 250000
    neighbors:
      - "149.112.50.3"
      - "2001:504:125:e1::3"
```
