### ISSUE TITLE
ASN Variable Usage throughout config

### ISSUE THREAD

**Issue by CloudieLLC** [natesales/pathvector#181]
This many not be applicable to most users, but say.. I've got a large community set for a each downstream user, for future usage etc. 
to avoid situations for human error, the ability to utilize a variable for ``asn:`` elsewhere for example. 

```
  LXC_2021:
    asn: 123456
    as-set: AS123456
    listen6: 2602:fba1:100::1
    template: downstream_lxc_default
    filter-rpki: false
    add-on-import: 
      - 924:1123456 #From Downstream User
    neighbors:
      - 2602:fba1:100:beef::11:1
```

to

```
  LXC_2021:
    asn: 123456
    as-set: AS${asn}
    listen6: 2602:fba1:100::1
    template: downstream_lxc_default
    filter-rpki: false
    add-on-import: 
      - 924:1:${asn}#From Downstream User
    neighbors:
      - 2602:fba1:100:beef::11:1
  ```

This could be used for a number of things, later down the track etc. and just something to think about since i was sitting there rewriting my config file.
