### ISSUE TITLE
Port 179 does not seem to be responsive even internally

### ISSUE THREAD

**Issue by xfy777** [natesales/pathvector#187]
**Describe the bug**
BGP sessions are failing to establish on our LAN to a router using pathvector. 
Telnet into port 179 even locally on the same machine does not work despite specifically even adding ip table rules to accept ALL traffic. The  IPs are pingable on both ends.

**Environment**

1. Pathvector 6.3.2
2. Ubuntu 22.04.2 LTS
3. Config
```yaml
asn: 57308
router-id: 23.142.248.47
source6: 2602:291::9ed3
source4: 23.142.248.47
prefixes:
  - 2a05:dfc1:4e00::/40

templates:
  upstream:
    allow-local-as: true
    announce: [ "57308,15", "57308:0:15" ]
    announce-default: false
    remove-all-communities: 57308
    local-pref6: 80
    add-on-import: [ "57308,12", "57308:0:12" ]
    announce-originated:  true

  downstream:
    filter-irr: true
    allow-blackhole-community: true
    filter-transit-asns: true
    auto-import-limits: true
    auto-as-set: true
    announce: [ "57308,15", "57308:0:15" ]
    announce-default: true
    remove-all-communities: 57308
    local-pref6: 200
    add-on-import: [ "57308,15", "57308:0:15" ]

peers:
  Upstream:
    asn: 393577
    template: upstream
    neighbors:
      - 2602:291::1
```

4. Telnet
```
telnet 127.0.0.1 179
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Expected behavior**
I would expect the router to establish sessions as it should, but they are stuck in idle.
```
pathvector status
PEER      AS      NEIGHBOR     STATE  IN      OUT  SINCE                INFO        
static6   -       -            up     1       0    2023-07-21 21:16:10               
default4  -       -            up     1       0    2023-07-21 21:16:10               
default6  -       -            up     1       0    2023-07-21 21:16:10               
device1   -       -            up     1       0    2023-07-21 21:16:10               
kernel1   -       -            up     0       2    2023-07-21 21:16:10               
kernel2   -       -            up     0       2    2023-07-21 21:16:10               
null4     -       -            up     1       0    2023-07-21 21:16:10               
null6     -       -            up     1       0    2023-07-21 21:16:10               
rpki1     -       -            up     364447  0    2023-07-21 21:20:40  Established  
Upstream  393577  2602:291::1  start               2023-07-21 21:16:10  Idle         
```

```
 sudo ss -tuln 'sport = :179'
Netid       State       Recv-Q       Send-Q             Local Address:Port               Peer Address:Port       Process       
root@57308:/home/sysop# 
```
