### ISSUE TITLE
import-limit6 set to 200,000 in BIRD config rather than 300,000 per configuration docs.

### ISSUE THREAD

**Issue by netstx** [natesales/pathvector#237]
**Describe the bug**

I have two transit peers for v6 and noticed one of the sessions was getting closed due to max prefixes, which happened to be slightly more than 200,000 (full table from provider). Other session at ~196k had not hit this limit yet.

Looking at the config documentation, "import-limit6" default is listed as 300,000, but when running ```pathvector generate``` it translates to "20000" in the generated BIRD config file when "import-limit6" not explicitly set in template or peer configuration within pacthvector's configuration file.

**Environment**

1. Output from `pathvector version`
```
Pathvector 6.3.2
Built c35220bf121f366ff05a51d93c6236e8c324d682 on 2023-06-11T07:03:14Z
No plugins
BIRD: ready.
```
3. OS version
```
root@core:~# uname -ar
Linux core 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
root@core:~# cat /etc/debian_version
12.5
root@core:~#
```
5. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
```yaml
templates:
  transit:
    filter-irr: false
    filter-rpki: false
    announce: [ "394414:0:15" ]
    remove-all-communities: 394414
    local-pref: 100
    auto-as-set: false
    auto-import-limits: false
    add-on-import: [ "394414:0:12" ]
```

**To Reproduce**

1. Copy this config to pathvector.yml...
2. Run `pathvector -v generate` and it processes correctly without any errors.
3. Open peer's BIRD config file and see that definition of v6 import limit is "200000".

**Expected behavior**

BIRD configuration for peer should have IPv6 limit set to 300,000 rather than 200,000:
```
...
define AS6939_HEV6_IMPORT_v6 = 200000;
...
```
after setting "import-limit6" in pathvector.yml to 400000, the generated BIRD config file for peer updates as expected:
```
...
define AS6939_HEV6_IMPORT_v6 = 400000;
...
```
