### ISSUE TITLE
AdvertiseHostname not passing validation

### ISSUE THREAD

**Issue by bonzi** [natesales/pathvector#256]
**Describe the bug**

Setting AdvertiseHostname results in pathvector failing to generate a valid config for bird.

```
FATA[0005] BIRD: BIRD validation error:
        import limit AS1234_COMPANY_IMPORT_v4 action disable;
        advertise hostname on;
        ^ syntax error, unexpected ADVERTISE
```

**Environment**
1. Output from `pathvector version`
```
pathvector version
Pathvector 6.3.2
Built c35220bf121f366ff05a51d93c6236e8c324d682 on 2023-06-11T07:03:14Z
No plugins
BIRD: ready.
```
2. OS version
Debian GNU/Linux 12 (bookworm) x86_64
3. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
```
hostname: router.as1234.net
...
  AS112:
    asn: 112
    description: AS112
    template: downstream
    neighbors:
      - 100.100.100.112
    announce-hostname: true
```
**To Reproduce**
1. Implement `hostname`, and `advertise-hostname` 
2. Run `pathvector g`
3. See error

**Expected behavior**
Pathvector should generate a valid config
