### ISSUE TITLE
Separate only-announce 

### ISSUE THREAD

**Issue by rapdodge** [natesales/pathvector#258]
**Describe the bug**

`only-announce` is failed to setup when it's having 2 AF (Address Family) at same time.

**Environment**

1. Output from `pathvector version`
```
Pathvector 6.3.2
Built c35220bf121f366ff05a51d93c6236e8c324d682 on 2023-06-11T07:03:14Z
No plugins
BIRD: ready.
```
2. OS version
Debian 12
3. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
```yaml
templates:
  ibgp:
    allow-local-as: true
    asn: 65535
    direct: true
    enforce-first-as: false
    enforce-peer-nexthop: false
    export-limit6: 10
    filter-irr: false
    filter-rpki: false
    import-limit6: 500000
    next-hop-self: true
    receive-limit6: 500000

peers:
  iBGP_Downstream:
    add-on-import:
      - 65535:1:4
    announce:
      - 65535:1:4
    disabled: false
    listen4: '172.16.0.1'
    listen6: 'fde3:1eaf:9fba:1::2'
    local-port: 209
    local-pref: 400
    neighbor-port: 209
    neighbors:
      - '172.16.0.2'
      - 'fde3:1eaf:9fba:1::1'
    only-announce:
      - '192.168.0.0/24'
      - '2001:db8::/32'
    template: ibgp
```

**To Reproduce**

1. Add peer config to pathvector.yml...
2. Run `pathvector g`
3. See error
```
DEBU[0011] Found error in ./AS65535.conf:xxx:xx message Mixed IPv4/IPv6 prefixes in prefix set
FATA[0011] BIRD: BIRD validation error:
  2001:db8::/32
            ]) then _reject("prefix not in only-announce list");
            ^ Mixed IPv4/IPv6 prefixes in prefix set
            if ((65535,1,4) ~ bgp_large_community) then accept;
```

**Expected behavior**

Separated config for v4 and v6
