### ISSUE TITLE
Standard Communities Not Working

### ISSUE THREAD

**Issue by potvinp** [natesales/pathvector#96]
**Describe the bug**
Error:
```
root@us-jfk1-0:~# pathvector generate
FATA[0000] Invalid import community: 212934,12
```
**Environment**
1. Output from `pathvector version`
```
root@us-jfk1-0:~# pathvector version
Pathvector 5.9.2 commit d47a7a8e516c6a258fbb5e071bac4dac221854a6 date 2022-01-16T21:56:59Z
No plugins
```
2. OS version
```
root@us-jfk1-0:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@us-jfk1-0:~# uname -r
5.10.0-9-amd64
```
3. Minimum reproducible example of your Pathvector config file formatted with [triple backticks with `yaml` language identifier](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
```yaml
templates:
  upstream:
    allow-local-as: true
    announce-communities: [ "212934:0:15" ]
    remove-all-communities: 212934
    local-pref: 80
    import-communities: [ "212934,12", "212934:0:12" ]
```
**To Reproduce**
1. Copy this config to pathvector.yml...
2. Run `pathvector generate`.
3. See error.

**Expected behavior**
Community would be accepted.
